---
- hosts: "{{ target_host_group | default('all')}}"
  serial: 1
  become: no
  handlers:
    - include: handlers/task_completion.yml
  gather_facts: no
  vars_files:
    - version.yml
  tags:
    - kwuxlab_ansible_common_pre_tasks

  roles:
    - role: authorized_host_recognition

  tasks:
    - name: store local playbook completion facts
      block:
        - name: Collect facts
          ansible.builtin.setup:

        - name: Create directory to store local facts
          ansible.builtin.file:
            state: directory
            recurse: yes
            path: "{{ ansible_local_facts_dir }}"
      become: yes

    - name: log the completion of this task
      command: /bin/true
      notify: complete playbook task