---
- name: restart consul
  service:
    name: consul
    state: restarted
- name: restart systemd-resolved
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: systemd-resolved