---
- hosts: "{{ target_host_group | default('all')}}"
  become: yes
  gather_facts: yes
  vars_files:
    - vars.yml
    - version.yml
  tags:
    - kwuxlab_ansible_maintenance_upgrade
  pre_tasks:
    - name: Collect facts
      ansible.builtin.setup:
      tags:
        - gather

  tasks:
    - name: Upgrade (install) each package
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
      loop: "{{ target_packages }}"