---
- hosts: "{{ target_host_group | default('all')}}"
  become: yes
  gather_facts: yes
  handlers:
    - include: handlers/task_completion.yml
  vars_files:
    - vars/shared.yml
    - version.yml
  tags:
    - kwuxlab_ansible_common_tailscale
  pre_tasks:
    - name: get all addresses
      debug:
        var: ansible_all_ipv4_addresses
    - name: debug default address ipv4
      debug:
        var: ansible_default_ipv4.address

    - name: Collect facts
      ansible.builtin.setup:
      tags:
        - gather

    - name: Load variables for this environment
      include_vars: "{{ env }}_environment.yml"
      tags:
        - gather
      no_log: true

    - name: Update apt cache if needed
      apt:
        update_cache: yes

  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_auth_key: "{{ target_tailscale_auth_key }}"
      tags:
        - tailscale

  tasks:
    - name: Allow the host to come back online
      wait_for:
        host: "{{ ansible_facts['nodename'] }}"
        port: 22
        state: started

    - name: log the completion of this task
      command: /bin/true
      notify: complete playbook task
