---
- name: Include global vars
  hosts:
    - "{{ target_host_group | default('all') }}"
  # Delegate fact gathering to individual playbooks
  gather_facts: no
  vars_files:
    - vars/main.yml
  tasks:
    - name: Set local ansible facts dir
      set_fact:
        ansible_local_facts_dir: "{{ ansible_local_facts_dir }}"

- name: Include version vars
  hosts:
    - "{{ target_host_group | default('all') }}"
  gather_facts: yes
  vars_files:
    - playbooks/kwuxlab_ansible_service_consul/version.yml

  tasks:
    - name: Set current playbook version
      set_fact:
        kwuxlab_ansible_service_consul_pb_version: "{{ kwuxlab_ansible_service_consul_pb_version }}"

- name: Gather facts for all kwuxlab hosts
  hosts:
    - "{{ target_host_group | default('all') }}"
  gather_facts: false
  tasks:
    - name: Setup
      ansible.builtin.setup:
      tags:
        - always

# Consul
- name: Restart consul
  hosts:
    - "{{ target_host_group | default('all') }}"
  gather_facts: false
  become: yes
  tasks:
    - name: Restart consul service
      service:
        name: consul
        state: restarted
