---
# Default host path to store local facts
ansible_local_facts_dir: "{{ ansible_local_facts_dir | default('/etc/ansible/facts.d') }}"

#
# Role-speciifc configuration
#

# Role:
#   name: `devsec.hardening.os_hardening`
#   source: https://github.com/dev-sec/ansible-collection-hardening/tree/master/roles/os_hardening

target_ufw_manage_defaults: false
