---
# Default host path to store local facts
ansible_local_facts_dir: "{{ ansible_local_facts_dir | default('/etc/ansible/facts.d') }}"

# Set the ansible python interpreter on host
ansible_python_interpreter: /usr/bin/python3

#
# Role-speciifc configuration
#

# Role:
#   name: `ansible-community.ansible-nomad`
#   source: https://github.com/ansible-community/ansible-nomad

# Target docker user (this is unused currently).
kwuxlab_docker_user: kwuxlab_dockerer

# Details @ https://hub.docker.com/r/bitnami/nomad
target_nomad_data_dir: "/var/nomad"
target_nomad_config_dir: "/etc/nomad.d"

target_nomad_cluster_name: "kwansible_nomad"
target_nomad_version: "1.2.6"

target_nomad_bind_address: "0.0.0.0"
target_nomad_resolved_host_tailscale_address: "{{ hostvars[inventory_hostname]['ansible_facts']['tailscale0']['ipv4']['address'] }}"
target_nomad_consul: "{{ target_nomad_resolved_host_tailscale_address }}:8500"

target_nomad_advertise_address: "{{ target_nomad_resolved_host_tailscale_address }}"

target_nomad_skip_ensure_all_hosts: yes
target_nomad_allow_purge_config: no # handy for resetting a particular node

# Matches tailscale ACLs
target_nomad_reserved_ports_list:
  - 22
  - 4646
  - 4647
  - 4648
  - 8001
  - 8200
  - 8201
  - 8300
  - 8301
  - 8302
  - 8500
  - 8600

target_nomad_reserved_ports: "{{ target_nomad_reserved_ports_list | map('string') | join(',') }}"
